name: ✅ Code Quality & Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: 🧹 Code Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.3

      - name: Install linting tools
        run: |
          pip install flake8 black

      - name: Run flake8
        run: flake8  etl tests

      - name: Check formatting with Black
        run: black --check etl tests

  test-ingest:
    name: 🧪 Test Ingestion Logic
    runs-on: ubuntu-latest
    needs: lint
    env:
      OPENAQ_API_KEY: ${{ secrets.OPENAQ_API_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run ingestion tests
        run: pytest tests/test_fetch_sensor_data.py

  test-preprocess:
    name: 🧪 Test Preprocessing Logic
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run preprocessing tests
        run: pytest tests/test_preprocess.py
